source 'https://github.com/CocoaPods/Specs.git'

target 'BitwiseFont', :exclusive => true do
  pod "BitwiseFont", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BitwiseFont", :path => "../"

  
end
